datastax/diagnostic-collection

- README.md
Minor formatting in the README file
> Minor formatting in the README file

- collect_node_diag.sh
Collect all types of JVM files. This fixed #3.
> Collect all types of JVM files

- README.md
Edit README to correct collect_diag.sh's -f description.
> Correct -f description for collect_diag.sh

- collect_diag.sh
- collect_node_diag.sh
- generate_diag.sh
* Add -k flag to opt in for collection
* Leverage the existing cassandra.yaml properties to formulate keytool command
* Store under conf/security/ for each node
* Only collect where applicable i.e. client_encryption and/or server_encryption enabled
> Collect SSL store data

- collect_node_diag.sh
- tests/integration/features/integration_tests.feature
- tests/integration/features/steps/integration_steps.py
Allows us to check what's running on the nodes aside from Cassandra
> Add extraction of the ps-aux output 

- README.md
Forgot to update the README in pull #16
> Add missing README entries for -k

- collect_diag.sh
Honor nodetool options while checking for status. Fixes #39
> Honor nodetool options while checking for status

- .github/workflows/oss_unencrypted.yml
Use 3.11.10 OSS C* for testing
> Use 3.11.10 OSS C* for testing

- ds-collector/collector.conf.in
- ds-collector/ds-collector
- ds-collector/rust-commands/collect-info.rs
Providing cqlsh host and arguments without the port crashes.
> Always specify the cqlsh port

- ds-collector/ds-collector
from https://github.com/datastax/diagnostic-collection/issues/63
> Retry the curl commands until they succeed

- ds-collector/ds-collector
Adds some fail-fast and additional OK/NOT messages.
> Support running on macos bastions

- ds-collector/ds-collector
> Make it easy to override the nodetool command (when initially discovering the cluster)

- ds-collector/ds-collector
> limited curl retry

- ds-collector/collector.conf.in
- ds-collector/ds-collector
> Add skipNodes option

- ds-collector/rust-commands/collect-info.rs
> Add chrony commands

- ds-collector/rust-commands/collect-info.rs
addresses https://github.com/datastax/diagnostic-collection/issues/75
> Do not `env` sensitive flags

- COPYRIGHT.txt
- ds-collector/COPYRIGHT.txt
- ds-collector/LICENSE.txt
(as that is bundled and distributed)
> Put license into ds-collector folder as well 

- ds-collector-tests/cluster-dse-k8s.make
- ds-collector-tests/cluster-one-node-vanilla-ssh-docker.make
- ds-collector-tests/cluster-vanilla-k8s.make
- ds-collector-tests/cluster-vanilla-ssh-docker.make
> Each integration test to specifically name the generated bundles (and clean them)

- ds-collector/ds-collector
- ds-collector/rust-commands/collect-info.rs
prep for https://github.com/datastax/diagnostic-collection/issues/108
@mieslep, could you review please?
> Rename nodetoolHost to jmxHost, and also use it when jmx scraping

- ds-collector/ds-collector
> Ensure all C* datadirs are concatenated using spaces instead of commas for correct 'find' syntax

- ds-collector/collector.conf.in
- ds-collector/ds-collector
Added option to allow a container name to specified for k8s clusters where a single pod runs more than one container
> Support k8s pod running multiple containers

- Makefile
For testing purposes, we'd need the ability to point the AWS CLI to a custome endpoint, e.g. a localstack instance (which mocks all the AWS components the collector uses, including the secretsmanager).
The implementation proposed here uses env variables. If they are not set, nothing extra gets added into the call. If we set them (to a value like `--endpoint-url http://localstack:4566`), then it will automatically and transparently talk to the mocked AWS.
> Allow passing AWS endpoint URL to awscli

- .github/workflows/ds-collector-ci.yml
- Makefile
> Gmail blocks `tar -czf …` bundles, but not `tar -cf … ; gzip …` bundles

- ds-collector/ds-collector
- ds-collector/rust-commands/collect-info.rs
> Fix dse.yaml collection and the use of dse_conf_dir

- .github/workflows/ds-collector-ci.yml
- ds-collector-tests/cluster-dse-k8s.make
- ds-collector-tests/cluster-vanilla-k8s.make
- ds-collector-tests/cluster-vanilla-ssh-docker.make
- ds-collector-tests/docker-compose.yml
- ds-collector/ds-collector
Fixes copying of etc/* files (can't use glob).
Fixes running checks from a macos bastion
> Improve how we detect and can configure DSE/HCD

- Makefile
This permits the access_key for the secrets-manager to be write-only.
> Restrict interaction with the secrets-manager to creating the secret

- .github/workflows/ds-collector-ci.yml
- ds-collector/ds-collector
ref: https://datastax.slack.com/archives/C01E4057U9J/p1746515598839549
> Fix `-d` option and generation of collector_upload.complete marker
